# Generated by Django 6.0.4 on 2026-05-04 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Fan haqida ma'lumot")),
            ],
            options={
                'verbose_name': 'Fan ',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=10, verbose_name='Test turi')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar')),
                ('correct_count', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('wrong_count', models.IntegerField(verbose_name='Xato javoblar')),
                ('score_percentage', models.FloatField(verbose_name='Natija (%)')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Natija ',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A varianti')),
                ('option_b', models.CharField(max_length=255, verbose_name='B varianti')),
                ('option_c', models.CharField(max_length=255, verbose_name='C varianti')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1, verbose_name="To'g'ri javob")),
                ('test_type', models.CharField(choices=[('BSB', 'BSB (Baho nazorat)'), ('CHSB', 'CHSB (Choraklik nazorat)')], default='BSB', max_length=5, verbose_name='Test turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Savol ',
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
