# Generated by Django 6.0.4 on 2026-05-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Sozlamalari', max_length=50)),
                ('is_bsb_active', models.BooleanField(default=False, verbose_name='BSB testlarini yoqish')),
                ('is_chsb_active', models.BooleanField(default=False, verbose_name='CHSB testlarini yoqish')),
            ],
            options={
                'verbose_name': 'Test Sozlamasi',
                'verbose_name_plural': 'Test Sozlamalari',
            },
        ),
    ]
