# Generated by Django 6.0.4 on 2026-05-05 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='quizsettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('BSB', 'BSB'), ('CHSB', 'CHSB')], default='BSB', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='test_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='is_bsb_active',
            field=models.BooleanField(default=False, verbose_name='BSB yoqilgan'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='is_chsb_active',
            field=models.BooleanField(default=False, verbose_name='CHSB yoqilgan'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
