# Generated by Django 6.0.4 on 2026-05-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_description_alter_question_option_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-date_taken'], 'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='Jami savollar'),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='name',
            field=models.CharField(default='Test Sozlamalari', max_length=50, verbose_name='Sozlama nomi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255, verbose_name='A varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255, verbose_name='B varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255, verbose_name='C varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('BSB', 'BSB (Baho nazorat)'), ('CHSB', 'CHSB (Choraklik nazorat)')], default='BSB', max_length=5, verbose_name='Test turi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_count',
            field=models.IntegerField(default=0, verbose_name="To'g'ri javoblar"),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score_percentage',
            field=models.FloatField(verbose_name='Natija (%)'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='test_type',
            field=models.CharField(max_length=10, verbose_name='Test turi'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='Xato javoblar'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Fan haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fan nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('subject', 'text')},
        ),
    ]
