# Generated by Django 6.0.4 on 2026-05-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_options_alter_quizresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('BSB', 'BSB (Baho nazorat)'), ('CHSB', 'CHSB (Choraklik nazorat)')], default='BSB', max_length=10, verbose_name='Test turi'),
        ),
    ]
