"""
Django settings for quiz_system project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7%p%j39i#)--f$1i=fv^jze3e(c_-clx1@5nnoda%y(c$*z#d_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quiz.apps.QuizConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quiz_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quiz.context_processors.quiz_status', # O'zingizning processor shu yerga tushadi
            ],
        },
    },
]

WSGI_APPLICATION = 'quiz_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Foydalanuvchi login qilgandan keyin fanlar sahifasiga o'tadi
LOGIN_REDIRECT_URL = 'subjects'

# Logout qilgandan keyin login sahifasiga qaytadi
LOGOUT_REDIRECT_URL = 'login'

# Login sahifasining URL manzili
LOGIN_URL = 'login'

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Fayllarni yuklash uchun (Excel fayllar uchun kerak bo'ladi)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

LOGOUT_ON_GET = True
# Tizimga kirganda qayerga o'tish (masalan, fanlar sahifasiga)
LOGIN_REDIRECT_URL = 'subjects'

# Tizimdan chiqqanda qayerga o'tish (login sahifasiga)
LOGOUT_REDIRECT_URL = 'login'

# settings.py faylining oxiriga qo'shing
LOGOUT_ON_GET = True

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# settings.py oxirida:
LOGIN_REDIRECT_URL = 'subject_list'  # 'subjects' emas, 'subject_list' bo'lsin
LOGOUT_REDIRECT_URL = 'login'
# Foydalanuvchi brauzerni yopsa ham sessiya o'chib ketmaydi
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Sessiya amal qilish muddati (masalan, 1 yil soniyalarda)
SESSION_COOKIE_AGE = 31536000 

# Har bir harakatda sessiya muddati yangilanadi
SESSION_SAVE_EVERY_REQUEST = True
LOGIN_REDIRECT_URL = 'subject_list' # Kirgandan keyin qayerga o'tsin
LOGOUT_REDIRECT_URL = 'login'       # Chiqib ketgandan keyin qayerga o'tsin